[tox]
min_version = 4.0
env_list = py

[testenv]
description = Run unit tests
deps =
    pytest
    jubilant
    craft-providers
    tenacity
commands =
    pytest

[testenv:format]
description = Format python files with ruff
deps =
    ruff<1.0
commands =
    ruff format

[testenv:validate]
description = Validate python formatting with ruff
deps =
    ruff<1.0
commands =
    ruff format --check
    ruff check

[testenv:integration]
description = Run integration tests
changedir = {toxinidir}/tests/integration
sitepackages = true
deps =
    {[testenv]deps}
    # Needed for ROS launch_testing pytest plugin import
    lark
passenv =
    AMENT_PREFIX_PATH
    COLCON_PREFIX_PATH
    KEEP_MODELS
    KEEP_LXD_VMS
    LD_LIBRARY_PATH
    PYTHONPATH
    ROS_PACKAGE_PATH
commands =
    pytest -vv --log-cli-level=INFO --exitfirst

[testenv:terraform-format]
description = Format terraform files
commands =
    terraform fmt -recursive
allowlist_externals =
    terraform

[testenv:terraform-validate]
description = Validate terraform files
changedir = {toxinidir}/terraform
commands =
    terraform fmt -check -recursive -diff
    terraform init -backend=false -upgrade
    terraform validate
allowlist_externals =
    terraform

[testenv:terraform-test-rob-cos]
description = Test terraform rob-cos module
changedir = {toxinidir}/terraform/rob-cos/tests
commands =
    terraform init -upgrade
    terraform test -verbose
allowlist_externals =
    terraform

[testenv:terraform-test-rob-cos-microceph]
description = Test terraform rob-cos-microceph module
changedir = {toxinidir}/terraform/rob-cos-microceph/tests
commands =
    terraform init -upgrade
    python -c "import sys; sys.stderr.write('\n' + '='*80 + '\nSKIP: rob-cos-microceph tests\nReason: https://github.com/juju/terraform-provider-juju/issues/473\n' + '='*80 + '\n')"
    #terraform test -verbose
allowlist_externals =
    terraform

[testenv:terraform-test-microceph]
description = Test terraform microceph module
changedir = {toxinidir}/terraform/microceph/tests
commands =
    terraform init -upgrade
    terraform test -verbose
allowlist_externals =
    terraform

[testenv:terraform-test]
description = Test terraform modules
skip_install = true
deps =
commands =
    tox -e terraform-test-rob-cos,terraform-test-rob-cos-microceph,terraform-test-microceph
allowlist_externals =
    tox
