name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.yaml'
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
  integration:
    needs: terraform
    uses: ./.github/workflows/integration.yaml
