name: Terraform

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: Git ref to checkout
        required: false
        type: string
        default: ""
      run_terraform_docs:
        description: Run terraform-docs generation and push to PR branch
        required: false
        type: boolean
        default: true

jobs:
  terraform-docs:
    if: ${{ inputs.run_terraform_docs }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.checkout_ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1
      with:
        working-dir: terraform/rob-cos,terraform/rob-cos-microceph,terraform/microceph
        output-file: README.md
        output-method: inject
        git-push: "true"

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.checkout_ref }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tox
        sudo snap install terraform --classic

    - name: Validate Terraform
      run: |
        tox -e terraform-validate

  terraform-test:
    needs: terraform-validate
    uses: ./.github/workflows/juju-lxd-setup.yaml
    with:
      checkout_ref: ${{ inputs.checkout_ref }}
      command: tox -e terraform-test
